### ISSUE TITLE
Automatic app install like aurora droid root installer

### ISSUE THREAD

**Issue by ashwin-2309** [kitsunyan/foxy-droid#100] opened 2021-08-31 04:37 UTC
Foxy is the best client for me,but can you please try to ad root installer like aurora droid by which the apps will install automatically without clicking install.

**Comment by ItsHarper** [comment] 2021-08-31 05:56
Duplicate of #8

**Comment by machiav3lli** [comment] 2021-09-17 11:19
PR #101 fix this

**Closed as completed** 2023-03-23 09:56 UTC
