### ISSUE TITLE
Bug: repositories menu item is invisible

### ISSUE THREAD

**Issue by m3tro1d** [kitsunyan/foxy-droid#25] opened 2020-07-23 08:58 UTC
**Android version: 10**
**App version: 1.1**
So, the menu item with repositories settings has no caption, but it works though. It's not critical, but looks kinda ugly.

![Screenshot_20200723_114756_nya kitsunyan foxydroid](https://user-images.githubusercontent.com/40693425/88268404-1296d380-ccdb-11ea-90ec-5d59769e5443.jpg)

**Comment by kitsunyan** [comment] 2020-07-23 10:21
This looks like an issue in your custom Android implementation. I don't have direct access to how menus are displayed, only supply the list of items, and it shows them. If one of the items looks this weird, there it nothing I can do about it.
If it possible, contact your device manufacturer (Huawei, I guess?)

**Comment by m3tro1d** [comment] 2020-07-23 11:59
I see.. Anyway, thanks for the feedback. I'll try to do some research.
As for the android version, I have EMUI 10.0.0.203.

**Comment by andinus** [comment] 2020-07-24 12:24
Try checking if the text is there. There should be "Show layout bounds" or similar in developer options.

![20200724_175156](https://user-images.githubusercontent.com/62012039/88390732-60c5d880-cda8-11ea-93a4-a607b6a84064.jpg)

It could be that the font color is same as the background color or something.

**Comment by m3tro1d** [comment] 2020-07-24 12:59
It seems like there is no text at all.

![Screenshot_20200724_155509_nya kitsunyan foxydroid_1](https://user-images.githubusercontent.com/40693425/88393618-9f6a8b80-cdc6-11ea-980d-04bd0af0f7da.jpg)

**Comment by kitsunyan** [comment] 2020-07-24 13:06
This is probably caused by divider before this item. This feature is introduced in Android 9, and I'm using it for Android 9 and higher.
I can probably remove it from EMUI devices at all, though I don't like such hacks.

**Comment by kitsunyan** [comment] 2020-07-24 13:47
Can you test this [foxy-droid-release.zip](https://github.com/kitsunyan/foxy-droid/files/4972235/foxy-droid-release.zip)? It's an APK file, just rename it, github doesn't allow to attach APK files.

**Comment by m3tro1d** [comment] 2020-07-24 16:42
Yeah, sure. This version works fine.
![Screenshot](https://user-images.githubusercontent.com/40693425/88414281-44945c80-cde5-11ea-8174-a908b12de5e2.jpg)
Does it work on other devices though? Maybe there is no need in making a separate version for EMUI, and just use this.

**Comment by kitsunyan** [comment] 2020-07-24 21:09
> Maybe there is no need in making a separate version for EMUI

There won't be. It's a runtime check.

Fixed in https://github.com/kitsunyan/foxy-droid/commit/cc8766a870d0864b43b419e0ef388829b5f17180.

**Closed by kitsunyan** 2020-07-24 21:09 UTC

**Comment by m3tro1d** [comment] 2020-07-25 05:54
Ok. Thanks!
