### ISSUE TITLE
Some icon images never load no matter how many times I use the app

### ISSUE THREAD

**Issue by Pentaphon** [kitsunyan/foxy-droid#32] opened 2020-07-29 04:30 UTC
Here's an example. I've used this app for 3 days now. I've opened it 10 times so far to try it out. This icon never loads. 
![icon](https://user-images.githubusercontent.com/49374058/88756859-8d1b8500-d119-11ea-9eb0-824b673800b1.jpg)

**Comment by kitsunyan** [comment] 2020-07-30 04:57
The problem is that F-Droid can't extract XML icons, so any complex icons are broken now. Sometimes icons are available in metadata (like in case with K-9 Mail), but relying on these icons is not a complete solution. I'll add support for them.

**Comment by kitsunyan** [comment] 2020-07-30 15:34
Fixed in https://github.com/kitsunyan/foxy-droid/commit/3ec4eed53699f752c03dc4e4ab87c3e40daaec25

**Closed by kitsunyan** 2020-07-30 15:34 UTC
